apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.app.name }}-route
  namespace: {{ .Values.app.name }}
spec:
  parentRefs:
  - name: anycast-shared-gateway
    namespace: anycast-shared-gateway
  #hostnames:
  #  - apps.sandbox5470.opentlc.com
  #  - app1.sandbox.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /{{ .Values.app.name }}
    backendRefs:
    - name: {{ .Values.app.name }}
      port: {{ .Values.app.httproute.port }}
