---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: openshift-operators
spec:
  name: skupper-operator
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: {{ $.Values.rhsi.subscription.channel }}
  installPlanApproval: Automatic
...
