---
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    # Needed to allow argo to install along-side the MetalLB operator
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

