---
apiVersion: v2
name: gatewayapi
version: 1.0.0
kubeVersion: >= 4.19.0
description: Deploy anycast service Gateways and HTTPRoutes for the example applications
type: application
icon: https://gateway-api.sigs.k8s.io/images/logo/logo-text-horizontal.png
